#!/bin/bash
# Context Monitor - monitors session context window usage and triggers auto-summary

WORKSPACE="${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}"
MEMORY_DIR="$WORKSPACE/memory"
STATE_FILE="$MEMORY_DIR/.memory-manager-state.json"
LOG_FILE="$WORKSPACE/logs/context-monitor.log"

# Thresholds (adjustable)
WARNING_THRESHOLD=70
CRITICAL_THRESHOLD=85
AUTO_SUMMARY_THRESHOLD=80

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

log() {
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] $1" >> "$LOG_FILE"
}

# Get current context usage from session_status
get_context_usage() {
    # This needs to be called via OpenClaw's session_status tool
    # For now, we'll use a placeholder - in production, this would be replaced
    # with actual session_status parsing
    
    # Read from state file if available
    if [ -f "$STATE_FILE" ]; then
        local usage=$(jq -r '.context_usage // 0' "$STATE_FILE" 2>/dev/null)
        if [ -n "$usage" ] && [ "$usage" != "null" ]; then
            echo "$usage"
            return
        fi
    fi
    
    # Fallback: estimate from memory file sizes
    local total_chars=0
    for file in "$MEMORY_DIR"/*.md "$MEMORY_DIR"/episodic/*.md "$MEMORY_DIR"/semantic/*.md "$MEMORY_DIR"/procedural/*.md; do
        [ -f "$file" ] && total_chars=$((total_chars + $(wc -c < "$file" 2>/dev/null || echo 0)))
    done
    
    # Estimate: 128k context ≈ 512k chars (conservative)
    local usage_percent=$((total_chars * 100 / 512000))
    echo "$usage_percent"
}

# Update context usage in state file
update_context_usage() {
    local usage=$1
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
    if command -v jq >/dev/null 2>&1; then
        jq --arg ts "$timestamp" --argjson usage "$usage" \
            '.last_check = $ts | .context_usage = $usage' \
            "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"
    fi
}

# Generate summary of current session
generate_summary() {
    local summary_file="$MEMORY_DIR/episodic/$(date +%Y-%m-%d).md"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    
    echo "" >> "$summary_file"
    echo "## Auto-Summary ($timestamp)" >> "$summary_file"
    echo "" >> "$summary_file"
    echo "**Context usage reached ${AUTO_SUMMARY_THRESHOLD}% - generating summary**" >> "$summary_file"
    echo "" >> "$summary_file"
    echo "**Note**: This is a placeholder. In production, this would be replaced with" >> "$summary_file"
    echo "actual session content summary generated by the AI agent." >> "$summary_file"
    echo "" >> "$summary_file"
    
    log "Auto-summary generated at ${AUTO_SUMMARY_THRESHOLD}% context usage"
}

# Main monitoring logic
main() {
    # Ensure directories exist
    mkdir -p "$MEMORY_DIR"/episodic "$MEMORY_DIR"/semantic "$MEMORY_DIR"/procedural "$WORKSPACE/logs"
    
    # Initialize state file if needed
    if [ ! -f "$STATE_FILE" ]; then
        echo '{}' > "$STATE_FILE"
    fi
    
    # Get current context usage
    usage=$(get_context_usage)
    update_context_usage "$usage"
    
    echo "🧠 Context Monitor - Session Status"
    echo ""
    echo "Current context usage: ${usage}%"
    echo ""
    
    # Check thresholds
    if [ "$usage" -ge "$CRITICAL_THRESHOLD" ]; then
        echo -e "${RED}🚨 CRITICAL: ${usage}% context usage${NC}"
        echo ""
        echo "IMMEDIATE ACTION REQUIRED:"
        echo "  1. Session will be interrupted soon"
        echo "  2. Run: ~/.openclaw/skills/memory-manager/snapshot.sh"
        echo "  3. Use /new to start fresh session"
        echo "  4. Agent should auto-summarize before restart"
        echo ""
        log "CRITICAL: Context usage at ${usage}%"
        exit 2
        
    elif [ "$usage" -ge "$AUTO_SUMMARY_THRESHOLD" ]; then
        echo -e "${YELLOW}⚠️ WARNING: ${usage}% context usage${NC}"
        echo ""
        echo "Auto-summary triggered:"
        generate_summary
        echo "  ✓ Summary saved to episodic memory"
        echo ""
        echo "RECOMMENDED ACTIONS:"
        echo "  1. Review summary in: $MEMORY_DIR/episodic/$(date +%Y-%m-%d).md"
        echo "  2. Consider using /new to refresh context"
        echo "  3. Agent will continue with summarized context"
        echo ""
        log "WARNING: Context usage at ${usage}%, auto-summary generated"
        exit 1
        
    elif [ "$usage" -ge "$WARNING_THRESHOLD" ]; then
        echo -e "${YELLOW}⚠️ CAUTION: ${usage}% context usage${NC}"
        echo ""
        echo "Approaching summary threshold (${AUTO_SUMMARY_THRESHOLD}%)"
        echo "Monitor closely and prepare for auto-summary"
        echo ""
        log "CAUTION: Context usage at ${usage}%"
        exit 0
        
    else
        echo -e "${GREEN}✅ Safe: ${usage}% context usage${NC}"
        echo ""
        echo "Next check recommended at ${WARNING_THRESHOLD}%"
        echo "Auto-summary will trigger at ${AUTO_SUMMARY_THRESHOLD}%"
        echo ""
        log "Safe: Context usage at ${usage}%"
        exit 0
    fi
}

# Run main function
main
